version: '3.8'
services: 
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./ATuCasaBackend
    ports: 
      - 8080:80
  clients:
    build: 
      dockerfile: Dockerfile
      context: ./ATuCasaClients
    ports:
      - 8081:4200
  users:
    build: 
      dockerfile: Dockerfile
      context: ./ATuCasaUsers
    ports: 
      - 80:4200



  